export const GET_PAYMENT_SUPPLIERS = {
  type: 'object',
  properties: {
    links: {
      type: 'object',
      properties: {
        next: { type: ['null', 'string'] },
        previous: { type: ['null', 'string'] },
      },
      required: ['next', 'previous'],
      additionalProperties: false,
    },
    count: { type: 'number' },
    page_number: { type: 'number' },
    total_pages: { type: 'number' },
    results: {
      type: 'array',
      minItems: 0,
      maxItems: 50,
      items: {
        type: 'object',
        properties: {
          id: { type: 'string' },
          is_main: { type: 'boolean' },
          payment_method_type: { type: 'number' },
          bank_id: { type: ['null', 'string'] },
          bank_branch_id: { type: ['null', 'string'] },
          account_type: { type: ['null', 'number'] },
          account_number: { type: ['null', 'string'] },
          account_name: { type: ['null', 'string'] },
          charged_by: { type: ['null', 'string'] },
          company_bank_account_id: { type: ['null', 'string'] },
        },
        required: [
          'id',
          'is_main',
          'payment_method_type',
          'bank_id',
          'bank_branch_id',
          'account_type',
          'account_number',
          'account_name',
          'charged_by',
          'company_bank_account_id',
        ],
        additionalProperties: false,
      },
    },
  },
  required: ['links', 'count', 'page_number', 'total_pages', 'results'],
  additionalProperties: false,
};

export const POST_PAYMENT_SUPPLIER = {
  type: 'object',
  properties: {
    id: { type: 'string' },
    is_main: { type: 'boolean' },
    payment_method_type: { type: 'number' },
    bank_id: { type: ['null', 'string'] },
    bank_branch_id: { type: ['null', 'string'] },
    account_type: { type: ['null', 'number'] },
    account_number: { type: ['null', 'string'] },
    account_name: { type: ['null', 'string'] },
    charged_by: { type: ['null', 'string'] },
    company_bank_account_id: { type: ['null', 'string'] },
  },
  required: [
    'id',
    'is_main',
    'payment_method_type',
    'bank_id',
    'bank_branch_id',
    'account_type',
    'account_number',
    'account_name',
    'charged_by',
    'company_bank_account_id',
  ],
  additionalProperties: false,
};

export const GET_PAYMENT_SUPPLIER = {
  type: 'object',
  properties: {
    id: { type: 'string' },
    is_main: { type: 'boolean' },
    payment_method_type: { type: 'number' },
    bank_id: { type: ['null', 'string'] },
    bank_branch_id: { type: ['null', 'string'] },
    account_type: { type: ['null', 'number'] },
    account_number: { type: ['null', 'string'] },
    account_name: { type: ['null', 'string'] },
    charged_by: { type: ['null', 'string'] },
    company_bank_account_id: { type: ['null', 'string'] },
  },
  required: [
    'id',
    'is_main',
    'payment_method_type',
    'bank_id',
    'bank_branch_id',
    'account_type',
    'account_number',
    'account_name',
    'charged_by',
    'company_bank_account_id',
  ],
  additionalProperties: false,
};

export const PUT_PAYMENT_SUPPLIER = {
  type: 'object',
  properties: {
    id: { type: 'string' },
    is_main: { type: 'boolean' },
    payment_method_type: { type: 'number' },
    bank_id: { type: ['null', 'string'] },
    bank_branch_id: { type: ['null', 'string'] },
    account_type: { type: ['null', 'number'] },
    account_number: { type: ['null', 'string'] },
    account_name: { type: ['null', 'string'] },
    charged_by: { type: ['null', 'string'] },
    company_bank_account_id: { type: ['null', 'string'] },
  },
  required: [
    'id',
    'is_main',
    'payment_method_type',
    'bank_id',
    'bank_branch_id',
    'account_type',
    'account_number',
    'account_name',
    'charged_by',
    'company_bank_account_id',
  ],
  additionalProperties: false,
};
