version: 2.1

orbs:
  node: circleci/node@5.1.0

commands:
  notify-slack:
    parameters:
      message:
        type: string
      slackWebHookId:
        type: string
    steps:
      - run:
          name: Detecting job status (PASS)
          command: echo "status=good" >> $BASH_ENV
          when: on_success
      - run:
          name: Detecting job status (FAIL)
          command: echo "status=danger" >> $BASH_ENV
          when: on_fail
      - run:
          name: Sending Notification to slack
          when: always
          command: |
            source $BASH_ENV
            message=$(echo "<<parameters.message>>" | jq -Rr @uri)
            dirName="${CIRCLE_PROJECT_REPONAME}_${CIRCLE_BRANCH}_${CIRCLE_BUILD_NUM}"
            reportLink="https://test-report.mfvn.dev/${dirName}/index.html"
            reportLinkDetails="https://test-report.mfvn.dev/${dirName}"
            requestParams="status=${status}&buildUrl=${CIRCLE_BUILD_URL}&message=${message}&repoName=${CIRCLE_PROJECT_REPONAME}&branch=${CIRCLE_BRANCH}&buildNum=${CIRCLE_BUILD_NUM}&jobName=${CIRCLE_JOB}&reportLink=${reportLink}&reportLinkDetails=${reportLinkDetails}&slackWebHookId=<<parameters.slackWebHookId>>"
            requestURL="${APP_SCRIPT_URL}?${requestParams}"
            curl -L -X GET "${requestURL}"

jobs:
  klavis-automation-test:
    machine: true
    resource_class: moneyforwardvietnam/qa-runner
    steps:
      - node/install
      - checkout
      - run: node --version
      - run: npm i -D @playwright/test
      - run: npx playwright install
      - run: npx playwright install chrome
      - run:
          name: 'Run automation test'
          command: 'npm test'
      - run:
          name: Copy reports result to public folder
          when: always
          command: |
            mkdir -p /var/www/html/${CIRCLE_PROJECT_REPONAME}_${CIRCLE_BRANCH}_${CIRCLE_BUILD_NUM}
            cp -R /var/opt/circleci/workdir/test-results/reports/* /var/www/html/${CIRCLE_PROJECT_REPONAME}_${CIRCLE_BRANCH}_${CIRCLE_BUILD_NUM}
      - run:
          name: View Logs URL
          when: always
          command: echo "https://test-report.mfvn.dev/${CIRCLE_PROJECT_REPONAME}_${CIRCLE_BRANCH}_${CIRCLE_BUILD_NUM}"
      - store_artifacts:
          path: /var/opt/circleci/workdir/test-results/reports/index.html
      - notify-slack:
          message: 'Automation Test'
          slackWebHookId: 'B05FH8MAH8D/Ym1j8Q1QGUrFMSN2jEDOZFp3'

workflows:
  kl-workflow:
    jobs:
      - klavis-automation-test:
          filters:
            branches:
              only:
                - main
